#!/bin/bash

echo "==================================="
echo "GitHub Repository Setup for SWS Engineering Portal"
echo "==================================="
echo ""
echo "This script will help you create a GitHub repository and deploy to Vercel."
echo ""
echo "STEP 1: Create GitHub Repository"
echo "---------------------------------"
echo "1. Go to: https://github.com/new"
echo "2. Sign in as Joseph Hawkins"
echo "3. Create a new repository with these settings:"
echo "   - Repository name: sws-engineering-portal"
echo "   - Description: South West Steam Engineering Portal - Project Management System"
echo "   - Private repository: Yes (recommended)"
echo "   - DO NOT initialize with README, .gitignore, or license"
echo ""
echo "Press Enter when you've created the repository..."
read

echo ""
echo "STEP 2: Push to GitHub"
echo "---------------------------------"
echo "Enter your GitHub username (e.g., josephhawkins):"
read GITHUB_USERNAME

echo ""
echo "Adding GitHub remote..."
git remote add origin https://github.com/$GITHUB_USERNAME/sws-engineering-portal.git

echo "Pushing to GitHub..."
echo "You may be prompted for your GitHub credentials."
echo ""
git branch -M main
git push -u origin main

echo ""
echo "✅ Code pushed to GitHub!"
echo ""
echo "STEP 3: Deploy to Vercel"
echo "---------------------------------"
echo "1. Go to: https://vercel.com/new"
echo "2. Click 'Import Git Repository'"
echo "3. Select: $GITHUB_USERNAME/sws-engineering-portal"
echo "4. Configure project:"
echo "   - Framework Preset: Next.js (auto-detected)"
echo "   - Root Directory: ./ (leave as default)"
echo "   - Build Command: npm run build (leave as default)"
echo ""
echo "5. Add Environment Variables (click 'Add' for each):"
echo ""
echo "   DATABASE_URL"
echo "   Value: postgresql://user:pass@host:5432/dbname"
echo ""
echo "   JWT_SECRET"
echo "   Value: $(openssl rand -base64 32)"
echo ""
echo "   NEXTAUTH_URL"
echo "   Value: https://your-app-name.vercel.app"
echo ""
echo "   NEXTAUTH_SECRET"
echo "   Value: $(openssl rand -base64 32)"
echo ""
echo "   EMAIL_HOST"
echo "   Value: smtp.gmail.com"
echo ""
echo "   EMAIL_PORT"
echo "   Value: 587"
echo ""
echo "   EMAIL_SECURE"
echo "   Value: false"
echo ""
echo "   EMAIL_USER"
echo "   Value: your-email@gmail.com"
echo ""
echo "   EMAIL_PASS"
echo "   Value: your-app-specific-password"
echo ""
echo "   EMAIL_FROM"
echo "   Value: noreply@swsteamengineering.co.uk"
echo ""
echo "   BLOB_READ_WRITE_TOKEN"
echo "   Value: (get from Vercel dashboard > Storage > Blob)"
echo ""
echo "6. Click 'Deploy'"
echo ""
echo "Your site will be live at: https://your-app-name.vercel.app"
echo ""
echo "Portal URLs:"
echo "- Engineering: https://your-app-name.vercel.app/portal"
echo "- Customer: https://your-app-name.vercel.app/customer"
echo ""
echo "==================================="
echo "Repository: https://github.com/$GITHUB_USERNAME/sws-engineering-portal"
echo "===================================="